name: voice_message_package
description: Flutter package to play voice message in chats.
version: 0.0.74
homepage: https://github.com/mehranshoqi/voice_message_player

environment:
  sdk: ">=3.4.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  just_audio: ^0.9.31
  syncfusion_flutter_sliders: 25.1.40
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



